### ISSUE TITLE
Cannot assign value of type 'UIBarButtonItem' to type 'UIView?'

### ISSUE THREAD

**Issue by takasurazeem** [anas-p/ImagePicker#1]
My sender is of type UIBarButtonItem

alert.popoverPresentationController?.sourceView = sender
// ^ Cannot assign value of type 'UIBarButtonItem' to type 'UIView?'
alert.popoverPresentationController?.sourceRect = sender.bounds
// ^ Value of type 'UIBarButtonItem' has no member 'bounds'

The following two lines give the two errors, is there a fix for that? or I have to use UIButton instead?

**Comment by anas-p** [comment]
I'm recommending this [link](https://stackoverflow.com/questions/14318368/uibarbuttonitem-how-can-i-find-its-frame) for finding the frame of UIBarButtonItem. Still there any issue, Let me know.
