### ISSUE TITLE
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) does not call

### ISSUE THREAD

**Issue by MohsenMoghimi** [anas-p/ImagePicker#3]
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) does not call . i did set imagepicker.delegate to self . but it still does not call .

**Comment by 3213853365** [comment]
Use this method if you are using above 4.
> func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
>     if let pickedImage = info[UIImagePickerController.InfoKey.originalImage] as? UIImage {
>     }
>     dismiss(animated: true, completion: nil)
> }
